set -g default-terminal "xterm-256color"

# TPM (Plugin manager)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

## Status Bar powerline theme
set -g @plugin 'wfxr/tmux-power'
set -g @tmux_power_theme 'gold'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
