# Includes
include catppuccin_mocha.conf 

# Fonts
font_family DaddyTimeMono Nerd Font Mono Book
bold_font auto
italic_font auto
bold_italic_font auto
font_size 22.0
background_opacity 0.7

# Customization
hide_window_decorations titlebar-only
window_padding_width 10

# Shortcuts
map ctrl+shift+q no_op
map ctrl+shift+w no_op
