import = [
        '~/.config/alacritty/themes/gruvbox-light.toml',
]

shell = "/bin/zsh"
live_config_reload = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
blur = true
opacity = 0.8

[font]
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Regular" }
bold = { family = "FantasqueSansM Nerd Font Mono", style = "Bold" }
italic = { family = "FantasqueSansM Nerd Font Mono", style = "Italic" }
size = 24.0

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
osc52 = "CopyPaste"
